CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'admin'
);

INSERT INTO users (username, password, role)
SELECT 'admin', '1234', 'admin'
WHERE NOT EXISTS (
  SELECT 1 FROM users WHERE username = 'admin'
);

CREATE TABLE IF NOT EXISTS dealers (
  id SERIAL PRIMARY KEY,
  dealer_code VARCHAR(30) DEFAULT NULL,
  dealer_name VARCHAR(100) NOT NULL,
  party_type VARCHAR(20) NOT NULL DEFAULT 'PACS',
  phone VARCHAR(20) NOT NULL,
  address TEXT NOT NULL,
  district VARCHAR(100) DEFAULT NULL,
  state VARCHAR(100) DEFAULT NULL,
  credit_limit NUMERIC(12,2) DEFAULT 0,
  active_flag CHAR(1) DEFAULT 'Y',
  total_selling_bags INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS products (
  id SERIAL PRIMARY KEY,
  product_code VARCHAR(30) DEFAULT NULL,
  name VARCHAR(100) NOT NULL,
  category VARCHAR(100) DEFAULT NULL,
  unit VARCHAR(30) DEFAULT NULL,
  hsn VARCHAR(20) DEFAULT NULL,
  mrp NUMERIC(10,2) DEFAULT 0,
  rate NUMERIC(10,2) NOT NULL,
  gst NUMERIC(5,2) DEFAULT 0,
  active_qty INTEGER DEFAULT 0,
  active_flag CHAR(1) DEFAULT 'Y'
);

CREATE TABLE IF NOT EXISTS employees (
  id SERIAL PRIMARY KEY,
  emp_code VARCHAR(30) DEFAULT NULL,
  name VARCHAR(100) NOT NULL,
  mobile VARCHAR(20) NOT NULL,
  designation VARCHAR(100) NOT NULL,
  region_district VARCHAR(150) DEFAULT NULL,
  zm_name VARCHAR(100) DEFAULT NULL,
  active_flag CHAR(1) DEFAULT 'Y',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
  id SERIAL PRIMARY KEY,
  order_date TIMESTAMP NOT NULL,
  dealer_id INTEGER NOT NULL REFERENCES dealers(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  employee_id INTEGER DEFAULT NULL REFERENCES employees(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  qty INTEGER NOT NULL,
  rate NUMERIC(10,2) NOT NULL,
  amount NUMERIC(10,2) NOT NULL,
  payment_type VARCHAR(20) NOT NULL,
  credit_due_date DATE DEFAULT NULL,
  payment_status VARCHAR(30) DEFAULT 'Pending',
  paid_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
  outstanding NUMERIC(10,2) NOT NULL DEFAULT 0,
  delivered_qty INTEGER DEFAULT 0,
  pending_qty INTEGER DEFAULT 0,
  recovery_due_date DATE DEFAULT NULL,
  confirmation_message VARCHAR(255) DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
);

CREATE TABLE IF NOT EXISTS payments (
  id SERIAL PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE,
  amount NUMERIC(10,2) NOT NULL,
  mode VARCHAR(30) DEFAULT NULL,
  reference_no VARCHAR(100) DEFAULT NULL,
  status VARCHAR(30) DEFAULT 'Paid',
  notes TEXT DEFAULT NULL,
  date TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS dispatch (
  id SERIAL PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE,
  dispatch_qty INTEGER NOT NULL DEFAULT 0,
  invoice_no VARCHAR(50) DEFAULT NULL,
  transport_name VARCHAR(100) NOT NULL,
  vehicle_no VARCHAR(50) DEFAULT NULL,
  driver_name VARCHAR(100) DEFAULT NULL,
  driver_phone VARCHAR(20) DEFAULT NULL,
  lr_no VARCHAR(50) DEFAULT NULL,
  eway_bill VARCHAR(100) DEFAULT NULL,
  dispatch_remarks TEXT DEFAULT NULL,
  dispatch_date TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS advance_payments (
  id SERIAL PRIMARY KEY,
  dealer_id INTEGER NOT NULL REFERENCES dealers(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  amount NUMERIC(12,2) NOT NULL,
  mode VARCHAR(30) DEFAULT 'NEFT/RTGS',
  reference_no VARCHAR(100) DEFAULT NULL,
  remarks TEXT DEFAULT NULL,
  payment_date TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS advance_payment_adjustments (
  id SERIAL PRIMARY KEY,
  advance_payment_id INTEGER NOT NULL REFERENCES advance_payments(id) ON DELETE CASCADE ON UPDATE CASCADE,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE,
  payment_id INTEGER DEFAULT NULL REFERENCES payments(id) ON DELETE SET NULL ON UPDATE CASCADE,
  adjusted_amount NUMERIC(12,2) NOT NULL,
  adjustment_date TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transport (
  id SERIAL PRIMARY KEY,
  transport_name VARCHAR(100) NOT NULL,
  contact_person VARCHAR(100) NOT NULL,
  mobile VARCHAR(20) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS delivery_proof (
  id SERIAL PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE,
  image VARCHAR(255) NOT NULL,
  delivery_date DATE DEFAULT NULL,
  received_by VARCHAR(100) DEFAULT NULL,
  receiver_phone VARCHAR(20) DEFAULT NULL,
  condition_status VARCHAR(50) DEFAULT NULL,
  proof_link VARCHAR(255) DEFAULT NULL,
  employee_ref VARCHAR(50) DEFAULT NULL,
  delivered_qty INTEGER DEFAULT 0,
  pending_qty INTEGER DEFAULT 0,
  notes TEXT DEFAULT NULL,
  upload_date TIMESTAMP NOT NULL
);
